// This file is autogenerated by the hyperdb compiler
 

const { IndexEncoder, c, b4a } = require('hyperdb/runtime')
const { version, getEncoding, setVersion } = require('./messages.js')

const versions = { schema: version, db: 1 }

const helpers0 = require('../helpers.cjs')

// '@mia/conversations' collection key
const collection0_key = new IndexEncoder([
  IndexEncoder.STRING
], { prefix: 0 })

function collection0_indexify (record) {
  const a = record.id
  return a === undefined ? [] : [a]
}

// '@mia/conversations' value encoding
const collection0_enc = getEncoding('@mia/conversation/hyperdb#0')

// '@mia/conversations' reconstruction function
function collection0_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection0_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection0.decodedVersion = c.uint.decode(state)
  const record = collection0_enc.decode(state)
  record.id = key[0]
  return record
}
// '@mia/conversations' key reconstruction function
function collection0_reconstruct_key (keyBuf) {
  const key = collection0_key.decode(keyBuf)
  return {
    id: key[0]
  }
}

// '@mia/conversations'
const collection0 = {
  name: '@mia/conversations',
  id: 0,
  version: 1,
  encodeKey (record) {
    const key = [record.id]
    return collection0_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection0_key.encodeRange({
      gt: gt ? collection0_indexify(gt) : null,
      lt: lt ? collection0_indexify(lt) : null,
      gte: gte ? collection0_indexify(gte) : null,
      lte: lte ? collection0_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection0_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection0_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection0_reconstruct,
  reconstructKey: collection0_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@mia/messages' collection key
const collection1_key = new IndexEncoder([
  IndexEncoder.STRING
], { prefix: 1 })

function collection1_indexify (record) {
  const a = record.id
  return a === undefined ? [] : [a]
}

// '@mia/messages' value encoding
const collection1_enc = getEncoding('@mia/message/hyperdb#1')

// '@mia/messages' reconstruction function
function collection1_reconstruct (schemaVersion, keyBuf, valueBuf) {
  const key = collection1_key.decode(keyBuf)
  setVersion(schemaVersion)
  const state = { start: 0, end: valueBuf.byteLength, buffer: valueBuf }
  const type = c.uint.decode(state)
  if (type !== 0) throw new Error('Unknown collection type: ' + type)
  collection1.decodedVersion = c.uint.decode(state)
  const record = collection1_enc.decode(state)
  record.id = key[0]
  return record
}
// '@mia/messages' key reconstruction function
function collection1_reconstruct_key (keyBuf) {
  const key = collection1_key.decode(keyBuf)
  return {
    id: key[0]
  }
}

// '@mia/messages'
const collection1 = {
  name: '@mia/messages',
  id: 1,
  version: 1,
  encodeKey (record) {
    const key = [record.id]
    return collection1_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection1_key.encodeRange({
      gt: gt ? collection1_indexify(gt) : null,
      lt: lt ? collection1_indexify(lt) : null,
      gte: gte ? collection1_indexify(gte) : null,
      lte: lte ? collection1_indexify(lte) : null
    })
  },
  encodeValue (schemaVersion, collectionVersion, record) {
    setVersion(schemaVersion)
    const state = { start: 0, end: 2, buffer: null }
    collection1_enc.preencode(state, record)
    state.buffer = b4a.allocUnsafe(state.end)
    state.buffer[state.start++] = 0
    state.buffer[state.start++] = collectionVersion
    collection1_enc.encode(state, record)
    return state.buffer
  },
  trigger: null,
  reconstruct: collection1_reconstruct,
  reconstructKey: collection1_reconstruct_key,
  indexes: [],
  decodedVersion: 0
}

// '@mia/messages-by-conversation' collection key
const index2_key = new IndexEncoder([
  IndexEncoder.STRING,
  IndexEncoder.UINT,
  IndexEncoder.STRING
], { prefix: 2 })

// '@mia/messages-by-conversation' has the following schema defined key map
const index2_map = helpers0.mapMessageToConversation

function index2_indexify (record) {
  const arr = []

  const a0 = record.conversationId
  if (a0 === undefined) return arr
  arr.push(a0)

  const a1 = record.timestamp
  if (a1 === undefined) return arr
  arr.push(a1)

  return arr
}

// '@mia/messages-by-conversation'
const index2 = {
  name: '@mia/messages-by-conversation',
  version: 1,
  id: 2,
  encodeKey (record) {
    return index2_key.encode(index2_indexify(record))
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return index2_key.encodeRange({
      gt: gt ? index2_indexify(gt) : null,
      lt: lt ? index2_indexify(lt) : null,
      gte: gte ? index2_indexify(gte) : null,
      lte: lte ? index2_indexify(lte) : null
    })
  },
  encodeValue: (record) => index2.collection.encodeKey(record),
  encodeIndexKeys (record, context) {
    const mapped = index2_map(record, context)
    const keys = new Array(mapped.length)
    for (let i = 0; i < mapped.length; i++) {
      const mappedRecord = mapped[i]
      keys[i] = index2_key.encode([mappedRecord.conversationId, mappedRecord.timestamp, record.id])
    }
    return keys
  },
  reconstruct: (keyBuf, valueBuf) => valueBuf,
  offset: collection1.indexes.length,
  collection: collection1
}
collection1.indexes.push(index2)

const collections = [
  collection0,
  collection1
]

const indexes = [
  index2
]

module.exports = { versions, collections, indexes, resolveCollection, resolveIndex }

function resolveCollection (name) {
  switch (name) {
    case '@mia/conversations': return collection0
    case '@mia/messages': return collection1
    default: return null
  }
}

function resolveIndex (name) {
  switch (name) {
    case '@mia/messages-by-conversation': return index2
    default: return null
  }
}
