// This file is autogenerated by the hyperschema compiler
// Schema Version: 1
 
 
 

const { c } = require('hyperschema/runtime')

const VERSION = 1

 
let version = VERSION

// @mia/conversation
const encoding0 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    c.string.preencode(state, m.title)
    c.uint.preencode(state, m.createdAt)
    c.uint.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    c.string.encode(state, m.id)
    c.string.encode(state, m.title)
    c.uint.encode(state, m.createdAt)
    c.uint.encode(state, m.updatedAt)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.uint.decode(state)
    const r3 = c.uint.decode(state)

    return {
      id: r0,
      title: r1,
      createdAt: r2,
      updatedAt: r3
    }
  }
}

// @mia/message
const encoding1 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    c.string.preencode(state, m.conversationId)
    c.string.preencode(state, m.type)
    c.string.preencode(state, m.content)
    c.uint.preencode(state, m.timestamp)
    state.end++ // flags are fixed size

    if (m.toolName) c.string.preencode(state, m.toolName)
    if (m.toolInput) c.string.preencode(state, m.toolInput)
    if (m.toolResult) c.string.preencode(state, m.toolResult)
    if (m.toolStatus) c.string.preencode(state, m.toolStatus)
    if (m.routeInfo) c.string.preencode(state, m.routeInfo)
    if (m.toolExecutions) c.string.preencode(state, m.toolExecutions)
    if (m.metadata) c.string.preencode(state, m.metadata)
  },
  encode(state, m) {
    const flags =
      (m.toolName ? 1 : 0) |
      (m.toolInput ? 2 : 0) |
      (m.toolResult ? 4 : 0) |
      (m.toolStatus ? 8 : 0) |
      (m.routeInfo ? 16 : 0) |
      (m.toolExecutions ? 32 : 0) |
      (m.metadata ? 64 : 0)

    c.string.encode(state, m.id)
    c.string.encode(state, m.conversationId)
    c.string.encode(state, m.type)
    c.string.encode(state, m.content)
    c.uint.encode(state, m.timestamp)
    c.uint8.encode(state, flags)

    if (m.toolName) c.string.encode(state, m.toolName)
    if (m.toolInput) c.string.encode(state, m.toolInput)
    if (m.toolResult) c.string.encode(state, m.toolResult)
    if (m.toolStatus) c.string.encode(state, m.toolStatus)
    if (m.routeInfo) c.string.encode(state, m.routeInfo)
    if (m.toolExecutions) c.string.encode(state, m.toolExecutions)
    if (m.metadata) c.string.encode(state, m.metadata)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.string.decode(state)
    const r4 = c.uint.decode(state)
    const flags = c.uint8.decode(state)

    return {
      id: r0,
      conversationId: r1,
      type: r2,
      content: r3,
      timestamp: r4,
      toolName: (flags & 1) !== 0 ? c.string.decode(state) : null,
      toolInput: (flags & 2) !== 0 ? c.string.decode(state) : null,
      toolResult: (flags & 4) !== 0 ? c.string.decode(state) : null,
      toolStatus: (flags & 8) !== 0 ? c.string.decode(state) : null,
      routeInfo: (flags & 16) !== 0 ? c.string.decode(state) : null,
      toolExecutions: (flags & 32) !== 0 ? c.string.decode(state) : null,
      metadata: (flags & 64) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @mia/conversation/hyperdb#0
const encoding2 = {
  preencode(state, m) {
    c.string.preencode(state, m.title)
    c.uint.preencode(state, m.createdAt)
    c.uint.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    c.string.encode(state, m.title)
    c.uint.encode(state, m.createdAt)
    c.uint.encode(state, m.updatedAt)
  },
  decode(state) {
    const r1 = c.string.decode(state)
    const r2 = c.uint.decode(state)
    const r3 = c.uint.decode(state)

    return {
      id: null,
      title: r1,
      createdAt: r2,
      updatedAt: r3
    }
  }
}

// @mia/message/hyperdb#1
const encoding3 = {
  preencode(state, m) {
    c.string.preencode(state, m.conversationId)
    c.string.preencode(state, m.type)
    c.string.preencode(state, m.content)
    c.uint.preencode(state, m.timestamp)
    state.end++ // flags are fixed size

    if (m.toolName) c.string.preencode(state, m.toolName)
    if (m.toolInput) c.string.preencode(state, m.toolInput)
    if (m.toolResult) c.string.preencode(state, m.toolResult)
    if (m.toolStatus) c.string.preencode(state, m.toolStatus)
    if (m.routeInfo) c.string.preencode(state, m.routeInfo)
    if (m.toolExecutions) c.string.preencode(state, m.toolExecutions)
    if (m.metadata) c.string.preencode(state, m.metadata)
  },
  encode(state, m) {
    const flags =
      (m.toolName ? 1 : 0) |
      (m.toolInput ? 2 : 0) |
      (m.toolResult ? 4 : 0) |
      (m.toolStatus ? 8 : 0) |
      (m.routeInfo ? 16 : 0) |
      (m.toolExecutions ? 32 : 0) |
      (m.metadata ? 64 : 0)

    c.string.encode(state, m.conversationId)
    c.string.encode(state, m.type)
    c.string.encode(state, m.content)
    c.uint.encode(state, m.timestamp)
    c.uint8.encode(state, flags)

    if (m.toolName) c.string.encode(state, m.toolName)
    if (m.toolInput) c.string.encode(state, m.toolInput)
    if (m.toolResult) c.string.encode(state, m.toolResult)
    if (m.toolStatus) c.string.encode(state, m.toolStatus)
    if (m.routeInfo) c.string.encode(state, m.routeInfo)
    if (m.toolExecutions) c.string.encode(state, m.toolExecutions)
    if (m.metadata) c.string.encode(state, m.metadata)
  },
  decode(state) {
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.string.decode(state)
    const r4 = c.uint.decode(state)
    const flags = c.uint8.decode(state)

    return {
      id: null,
      conversationId: r1,
      type: r2,
      content: r3,
      timestamp: r4,
      toolName: (flags & 1) !== 0 ? c.string.decode(state) : null,
      toolInput: (flags & 2) !== 0 ? c.string.decode(state) : null,
      toolResult: (flags & 4) !== 0 ? c.string.decode(state) : null,
      toolStatus: (flags & 8) !== 0 ? c.string.decode(state) : null,
      routeInfo: (flags & 16) !== 0 ? c.string.decode(state) : null,
      toolExecutions: (flags & 32) !== 0 ? c.string.decode(state) : null,
      metadata: (flags & 64) !== 0 ? c.string.decode(state) : null
    }
  }
}

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@mia/conversation':
      return encoding0
    case '@mia/message':
      return encoding1
    case '@mia/conversation/hyperdb#0':
      return encoding2
    case '@mia/message/hyperdb#1':
      return encoding3
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

module.exports = {
  resolveStruct,
  getStruct,
  getEnum,
  getEncoding,
  encode,
  decode,
  setVersion,
  version
}
