/**
 * SuggestionsService
 *
 * Maintains a persistent stack of up to 12 AI-generated project improvement
 * suggestions in ~/.mia/suggestions.json. Also generates a batch of 5 greeting
 * messages that cycle on the mobile home screen.
 *
 * Suggestions are generated by a lightweight utility dispatch (same pattern
 * as MemoryExtractor) and are specific to the user's projects based on context
 * gathered from memory facts, git state, and conversation history.
 *
 * Lifecycle:
 *   - On peer connect: maybeGenerate() fills the stack if stale (with cooldown)
 *   - On dismiss / complete: item is archived, no immediate regen
 *   - Periodic: setInterval in daemon/index.ts calls maybeGenerate() every 4h
 *
 * Reliability: the store is cached in memory after the first read so that
 * getActive(), getGreetings(), isStale(), dismiss(), and complete() never
 * block the event loop with synchronous I/O.  Writes are persisted
 * asynchronously (fire-and-forget with error logging) so mutations are
 * instantaneous from the caller's perspective.  A coalescing guard ensures
 * rapid sequential mutations produce at most one disk write.
 */

import { readFileSync, existsSync } from 'fs';
import { writeFile, readFile } from 'fs/promises';
import { join } from 'path';
import { homedir } from 'os';
import { withTimeout } from '../utils/with-timeout';

export interface Suggestion {
  id: string;
  name: string;
  description: string;
  createdAt: number;
}

interface SuggestionsStore {
  active: Suggestion[];
  /** Permanently dismissed — never suggested again */
  dismissed: Suggestion[];
  /** Completed (started) — never suggested again */
  completed: Suggestion[];
  lastGeneratedAt: number;
  /** AI-generated greeting messages that cycle on the mobile home screen */
  greetings: string[];
}

const STORE_PATH = join(homedir(), '.mia', 'suggestions.json');
const MAX_ACTIVE = 12;
/** Regenerate if the stack hasn't been refreshed in 4 hours */
const REGEN_INTERVAL_MS = 4 * 60 * 60 * 1000;
/** Minimum gap between generations to avoid waste (30 minutes) */
const MIN_REGEN_COOLDOWN_MS = 30 * 60 * 1000;
/** Maximum dismissed/completed history entries to include in the prompt */
const MAX_HISTORY_IN_PROMPT = 30;
/** Number of greeting messages to generate per batch */
const GREETINGS_COUNT = 5;
/**
 * Maximum number of dismissed/completed suggestions to retain on disk.
 * Only the most recent entries matter for dedup ("don't suggest again").
 * Without a cap these arrays grow unbounded over the daemon's lifetime,
 * causing ever-larger sync JSON reads/writes that block the event loop.
 */
const MAX_STORE_HISTORY = 200;
/**
 * Hard timeout for the utilityDispatch call inside generate().
 * Slightly longer than the dispatcher's own 3-minute timeout so the
 * dispatcher timeout fires first under normal conditions. This is a
 * safety net — if the dispatcher hangs for any reason, we still
 * recover and reset the `generating` flag.
 */
const GENERATION_TIMEOUT_MS = 4 * 60 * 1000;
/**
 * Hard timeout for a single async disk write in persistToDisk().
 * Prevents a stalled filesystem (NFS, FUSE, disk-full slow path) from
 * holding `persistInFlight = true` forever, which would permanently
 * block all future suggestion persistence for the daemon's lifetime.
 * 10 seconds is generous for a small JSON file on any healthy fs.
 */
const PERSIST_TIMEOUT_MS = 10_000;

function makeId(): string {
  const ts = String(Date.now()).padStart(15, '0');
  const rand = Math.random().toString(36).substring(2, 8);
  return `sug_${ts}_${rand}`;
}

// ── In-memory write-through cache ─────────────────────────────────────
// The store is tiny (a few KB) so keeping it fully in memory is safe.
// First access does one synchronous read (acceptable at daemon startup).
// All subsequent reads return the cached object — zero disk I/O.
// Writes update the cache immediately and persist asynchronously.

function emptyStore(): SuggestionsStore {
  return { active: [], dismissed: [], completed: [], lastGeneratedAt: 0, greetings: [] };
}

// ── Runtime schema validation ─────────────────────────────────────────────
// The store has been corrupted before (duplicate/malformed entries).
// Rather than silently propagating bad state we validate on load, discard
// individual malformed entries, and log a warning so the issue is visible.

/** Type-guard for a well-formed Suggestion object. */
function isValidSuggestion(v: unknown): v is Suggestion {
  if (v == null || typeof v !== 'object') return false;
  const s = v as Record<string, unknown>;
  return (
    typeof s.id === 'string' && s.id.length > 0 &&
    typeof s.name === 'string' && s.name.length > 0 &&
    typeof s.description === 'string' &&
    typeof s.createdAt === 'number' && Number.isFinite(s.createdAt)
  );
}

/**
 * Validate and repair a parsed store object.
 * - Ensures top-level fields have the correct types
 * - Filters out malformed suggestion/greeting entries
 * - Returns a guaranteed-safe SuggestionsStore (never throws)
 */
function validateStore(raw: unknown): SuggestionsStore {
  if (raw == null || typeof raw !== 'object') return emptyStore();

  const obj = raw as Record<string, unknown>;
  let repaired = false;

  // ── Suggestion arrays ────────────────────────────────────────────────
  const validateSuggestionArray = (key: string): Suggestion[] => {
    const arr = obj[key];
    if (!Array.isArray(arr)) {
      if (arr !== undefined) repaired = true;
      return [];
    }
    const valid = arr.filter(isValidSuggestion);
    if (valid.length !== arr.length) repaired = true;
    return valid;
  };

  const active    = validateSuggestionArray('active');
  const dismissed = validateSuggestionArray('dismissed');
  const completed = validateSuggestionArray('completed');

  // ── lastGeneratedAt ──────────────────────────────────────────────────
  let lastGeneratedAt = 0;
  if (typeof obj.lastGeneratedAt === 'number' && Number.isFinite(obj.lastGeneratedAt)) {
    lastGeneratedAt = obj.lastGeneratedAt;
  } else if (obj.lastGeneratedAt !== undefined) {
    repaired = true;
  }

  // ── Greetings ────────────────────────────────────────────────────────
  let greetings: string[] = [];
  if (Array.isArray(obj.greetings)) {
    greetings = obj.greetings.filter((g): g is string => typeof g === 'string' && g.trim().length > 0);
    if (greetings.length !== obj.greetings.length) repaired = true;
  } else if (obj.greetings !== undefined) {
    repaired = true;
  }

  if (repaired) {
    process.stderr.write('[Suggestions] Store contained malformed entries — repaired on load\n');
  }

  return { active, dismissed, completed, lastGeneratedAt, greetings };
}

let cachedStore: SuggestionsStore | null = null;

/**
 * Return the in-memory store, lazily initializing from disk on first call.
 * After initialization all reads are pure memory lookups — no file I/O.
 */
function loadStore(): SuggestionsStore {
  if (cachedStore) return cachedStore;

  // Cold start: one-time synchronous read (only happens once per daemon lifetime).
  try {
    if (existsSync(STORE_PATH)) {
      const raw = JSON.parse(readFileSync(STORE_PATH, 'utf-8'));
      cachedStore = validateStore(raw);
    } else {
      cachedStore = emptyStore();
    }
  } catch {
    cachedStore = emptyStore();
  }

  return cachedStore;
}

/**
 * Pre-warm the suggestions store by reading from disk asynchronously.
 *
 * WHY: loadStore() performs a cold-start synchronous read (existsSync +
 * readFileSync) on its very first invocation, which occurs when the first
 * P2P IPC message arrives.  Under I/O pressure (NFS stall, swap thrashing,
 * FUSE deadlock) those sync calls can block the entire event loop for seconds,
 * freezing P2P token delivery, watchdog heartbeats, and scheduler processing.
 *
 * Calling this at daemon startup — before any peer can connect — populates
 * cachedStore via async readFile so that loadStore() is always a cache hit
 * when it matters.  The existing sync loadStore() remains as an instant
 * fallback: if the prewarm hasn't finished (or failed), loadStore() falls
 * back to the sync path exactly as before.
 *
 * This function NEVER throws — all errors are caught and silently discarded.
 * A prewarm failure is non-critical: loadStore() will still work correctly.
 */
/**
 * Hard timeout (ms) for the prewarm readFile() call.
 *
 * prewarmSuggestionsStore() is fired-and-forgotten at daemon startup so that
 * the first call to loadStore() is always a memory-cache hit and never falls
 * back to the blocking readFileSync path.  Without a timeout, a hung
 * readFile() (NFS stall, FUSE deadlock, swap thrashing) leaves cachedStore
 * null indefinitely — causing the sync fallback to block the entire event
 * loop when the first P2P message triggers loadStore(), freezing token
 * delivery, watchdog heartbeats, and scheduler ticks.
 *
 * 5 s is generous for a small local file.  On timeout the catch block sets
 * cachedStore = emptyStore() so loadStore() is always a cache hit from that
 * point on — the sync path is never needed.
 */
const PREWARM_TIMEOUT_MS = 5_000;

export async function prewarmSuggestionsStore(): Promise<void> {
  // No-op if the cache is already populated (e.g. tests or double-call).
  if (cachedStore) return;

  try {
    // Wrapped in withTimeout: readFile() runs through libuv's thread pool
    // and can hang indefinitely under I/O pressure.  Without the timeout the
    // prewarm never completes, cachedStore stays null, and loadStore() falls
    // back to readFileSync — blocking the event loop under the same I/O
    // conditions that caused the hang.  On timeout we fall through to the
    // catch block which sets cachedStore = emptyStore(), ensuring loadStore()
    // is always a cache hit.
    const raw = JSON.parse(
      await withTimeout(readFile(STORE_PATH, 'utf-8'), PREWARM_TIMEOUT_MS, 'prewarmSuggestionsStore'),
    );
    // Guard against a concurrent sync loadStore() that may have run between
    // the await and this point — don't clobber a value that's already there.
    if (!cachedStore) {
      cachedStore = validateStore(raw);
    }
  } catch (err: unknown) {
    // ENOENT → store doesn't exist yet; timeout or other error → treat as empty.
    // Either way, populate the cache so loadStore() is always a cache hit.
    if (!cachedStore) {
      cachedStore = emptyStore();
    }
  }
}

/** True while an async write is in flight. */
let persistInFlight = false;
/** True if the store was mutated while a write was in flight (needs re-persist). */
let persistDirty = false;

/**
 * Persist the cached store to disk asynchronously.
 *
 * Coalesces rapid mutations: if a write is already in flight, the next
 * call sets a dirty flag and the in-flight write will re-persist once it
 * finishes.  This prevents piling up concurrent writeFile calls when
 * dismiss/complete is called in quick succession.
 *
 * The caller sees the mutation immediately (via the in-memory cache) so
 * there is no latency impact.  If the write fails the cache stays correct
 * and the next mutation will retry the persist.
 */
function saveStore(store: SuggestionsStore): void {
  try {
    // Cap history arrays to prevent unbounded growth over the daemon's
    // lifetime.  Keep the most recent entries — they are the ones that
    // matter for the dedup prompt ("don't suggest again").  This is the
    // single write path, so trimming here catches all mutation sites.
    if (store.dismissed.length > MAX_STORE_HISTORY) {
      store.dismissed = store.dismissed.slice(-MAX_STORE_HISTORY);
    }
    if (store.completed.length > MAX_STORE_HISTORY) {
      store.completed = store.completed.slice(-MAX_STORE_HISTORY);
    }

    // Update the in-memory cache immediately (synchronous, ~0 cost).
    cachedStore = store;

    // Coalesce: if a write is already in flight, just mark dirty.
    if (persistInFlight) {
      persistDirty = true;
      return;
    }

    persistToDisk();
  } catch (err) {
    process.stderr.write(`[Suggestions] Save (cache update) failed: ${err}\n`);
  }
}

/**
 * Fire-and-forget async disk write with coalescing retry.
 * Wrapped in try/catch so it never throws into the event loop.
 */
function persistToDisk(): void {
  if (!cachedStore) return;

  persistInFlight = true;
  persistDirty = false;

  const json = JSON.stringify(cachedStore, null, 2);

  withTimeout(writeFile(STORE_PATH, json, 'utf-8'), PERSIST_TIMEOUT_MS, 'Suggestions persist')
    .catch((err) => {
      // Nested try/catch: if process.stderr.write() throws (e.g. ERR_STREAM_DESTROYED
      // after the daemon closes the pipe), the throw would escape this .catch() callback
      // as a new unhandled rejection, counting toward the 10-rejection exit threshold.
      try { process.stderr.write(`[Suggestions] Async persist failed: ${err}\n`); } catch { /* stderr must not throw */ }
    })
    .finally(() => {
      persistInFlight = false;
      // If the store was mutated while we were writing, persist again
      // to pick up the latest state.
      if (persistDirty) {
        persistDirty = false;
        try {
          persistToDisk();
        } catch {
          // Safety net — persistToDisk must never throw.
        }
      }
    });
}

type UtilityDispatch = (prompt: string) => Promise<string>;
type BroadcastFn = (suggestions: Suggestion[], greetings: string[]) => void;

export class SuggestionsService {
  private utilityDispatch: UtilityDispatch | null = null;
  private broadcastFn: BroadcastFn | null = null;
  private generating = false;
  private workingDirectory = '';

  setUtilityDispatch(fn: UtilityDispatch): void {
    this.utilityDispatch = fn;
  }

  setBroadcast(fn: BroadcastFn): void {
    this.broadcastFn = fn;
  }

  setWorkingDirectory(dir: string): void {
    this.workingDirectory = dir;
  }

  /** True when an AI generation is currently in flight. */
  isGenerating(): boolean {
    return this.generating;
  }

  /** Return the current active suggestion stack (read-only). */
  getActive(): Suggestion[] {
    return loadStore().active;
  }

  /** Return the current greeting messages batch (read-only). */
  getGreetings(): string[] {
    return loadStore().greetings;
  }

  /** Return the full store for the management UI. */
  getFullStore(): { active: Suggestion[]; dismissed: Suggestion[]; completed: Suggestion[] } {
    const store = loadStore();
    return { active: store.active, dismissed: store.dismissed, completed: store.completed };
  }

  /**
   * Clear dismissed and completed history.
   * Returns the updated active list (unchanged — only history is wiped).
   */
  clearHistory(): Suggestion[] {
    const store = loadStore();
    store.dismissed = [];
    store.completed = [];
    saveStore(store);
    return store.active;
  }

  /**
   * Move a suggestion to the dismissed list.
   * Returns the updated active list. Regeneration happens on the periodic
   * 4-hour interval or next peer connect — not on every dismiss/complete.
   */
  dismiss(id: string): Suggestion[] {
    const store = loadStore();
    const idx = store.active.findIndex(s => s.id === id);
    if (idx !== -1) {
      const [removed] = store.active.splice(idx, 1);
      store.dismissed.push({ ...removed, createdAt: Date.now() });
      saveStore(store);
    }
    return store.active;
  }

  /**
   * Restore a dismissed suggestion back to the active list.
   * Returns the updated active list.
   */
  restore(id: string): Suggestion[] {
    const store = loadStore();
    const idx = store.dismissed.findIndex(s => s.id === id);
    if (idx !== -1) {
      const [removed] = store.dismissed.splice(idx, 1);
      store.active.push({ ...removed, createdAt: Date.now() });
      saveStore(store);
    }
    return store.active;
  }

  /**
   * Move a suggestion to the completed list.
   * Returns the updated active list. Regeneration happens on the periodic
   * 4-hour interval or next peer connect — not on every dismiss/complete.
   */
  complete(id: string): Suggestion[] {
    const store = loadStore();
    const idx = store.active.findIndex(s => s.id === id);
    if (idx !== -1) {
      const [removed] = store.active.splice(idx, 1);
      store.completed.push({ ...removed, createdAt: Date.now() });
      saveStore(store);
    }
    return store.active;
  }

  /** True if regeneration is needed and enough time has passed since the last generation. */
  isStale(): boolean {
    const store = loadStore();
    const elapsed = Date.now() - store.lastGeneratedAt;
    // Never regenerate within the cooldown window
    if (elapsed < MIN_REGEN_COOLDOWN_MS) return false;
    // Regenerate if underfull, greetings missing, or the refresh interval has expired
    return store.active.length < MAX_ACTIVE || store.greetings.length === 0 || elapsed > REGEN_INTERVAL_MS;
  }

  /**
   * Generate new suggestions only if the stack is stale or underfull.
   * Safe to call frequently — skips immediately if nothing to do.
   */
  async maybeGenerate(): Promise<void> {
    if (!this.isStale()) return;
    await this.generate();
  }

  /**
   * Call the AI to generate new suggestions + a batch of greeting messages
   * in a single prompt. Broadcasts to all connected mobile peers when done.
   */
  async generate(): Promise<void> {
    if (this.generating || !this.utilityDispatch) return;

    const store = loadStore();
    const needed = MAX_ACTIVE - store.active.length;
    if (needed <= 0 && store.greetings.length > 0) return;

    this.generating = true;
    try {
      const activeNames = store.active.map(s => `"${s.name}"`).join(', ');
      const dismissedNames = store.dismissed
        .slice(-MAX_HISTORY_IN_PROMPT)
        .map(s => `"${s.name}"`)
        .join(', ');
      const completedNames = store.completed
        .slice(-MAX_HISTORY_IN_PROMPT)
        .map(s => `"${s.name}"`)
        .join(', ');

      const neededSuggestions = Math.max(needed, 0);

      const prompt = `You are an AI assistant for a software developer. Generate two things in a single JSON response.

Working directory: ${this.workingDirectory || 'unknown'}

1. SUGGESTIONS: Generate exactly ${neededSuggestions > 0 ? neededSuggestions : 'no new'} distinct, concrete improvement task suggestion${neededSuggestions !== 1 ? 's' : ''} for the developer's current projects.
   - CRITICAL: Every suggestion MUST have a UNIQUE name — no two suggestions can share the same name
   - Each must be immediately actionable (not vague)
   - Focus on: code quality, test coverage, refactoring, documentation, performance, security, dependency hygiene, or tooling
   - Make it specific to what you know about the projects — avoid generic advice
   - Keep names short and imperative (5–8 words max)
   - Keep descriptions concise (1–2 sentences maximum)
   ${activeNames ? `\n   Do NOT duplicate these active suggestions: ${activeNames}` : ''}
   ${dismissedNames ? `\n   Do NOT suggest anything similar to these dismissed: ${dismissedNames}` : ''}
   ${completedNames ? `\n   Do NOT suggest anything similar to these completed: ${completedNames}` : ''}

2. GREETINGS: Generate exactly ${GREETINGS_COUNT} short, varied greeting messages for the home screen.
   - Warm, witty, and developer-flavoured
   - Each under 8 words
   - Vary the tone: one motivational, one curious, one playful, one focused, one understated
   - Do NOT use "Hello" or "Hi" — be more creative

Respond with ONLY a valid JSON object — no markdown fences, no explanation:
{
  "suggestions": [
    { "name": "Short imperative phrase", "description": "One or two sentences." }
  ],
  "greetings": [
    "What are we shipping today?",
    "Ready to break something good?",
    "Let's make the code better.",
    "Something needs fixing. Let's find it.",
    "Code, coffee, repeat."
  ]
}`;

      const result = await withTimeout(
        this.utilityDispatch(prompt),
        GENERATION_TIMEOUT_MS,
        'Suggestion generation'
      );

      // Strip any markdown fences the model might have added
      const cleaned = result.replace(/```[a-z]*\n?/gi, '').trim();
      const jsonMatch = cleaned.match(/\{[\s\S]*\}/);
      if (!jsonMatch) {
        process.stderr.write(`[Suggestions] No JSON object found in generation result\n`);
        return;
      }

      const parsed = JSON.parse(jsonMatch[0]) as {
        suggestions?: Array<{ name?: string; description?: string }>;
        greetings?: unknown[];
      };

      // Process suggestions — dedup by normalized name to prevent the AI
      // from generating duplicate suggestions in the same batch.
      const seenNames = new Set(
        [...store.active, ...store.dismissed.slice(-MAX_HISTORY_IN_PROMPT), ...store.completed.slice(-MAX_HISTORY_IN_PROMPT)]
          .map(s => s.name.toLowerCase().trim())
      );
      const newSuggestions: Suggestion[] = (parsed.suggestions ?? [])
        .filter(s => {
          if (!s.name || !s.description || typeof s.name !== 'string') return false;
          const normalized = (s.name as string).toLowerCase().trim();
          if (seenNames.has(normalized)) return false;
          seenNames.add(normalized);
          return true;
        })
        .slice(0, neededSuggestions)
        .map(s => ({
          id: makeId(),
          name: (s.name as string).trim().slice(0, 80),
          description: (s.description as string).trim().slice(0, 300),
          createdAt: Date.now(),
        }));

      // Process greetings
      const newGreetings: string[] = (parsed.greetings ?? [])
        .filter((g): g is string => typeof g === 'string' && g.trim().length > 0)
        .slice(0, GREETINGS_COUNT)
        .map(g => g.trim().slice(0, 60));

      // Reload to avoid clobbering concurrent writes
      const fresh = loadStore();
      if (newSuggestions.length > 0) {
        fresh.active.push(...newSuggestions);
      }
      if (newGreetings.length > 0) {
        fresh.greetings = newGreetings;
      }
      fresh.lastGeneratedAt = Date.now();
      saveStore(fresh);

      process.stderr.write(
        `[Suggestions] Generated ${newSuggestions.length} suggestion(s) and ${newGreetings.length} greeting(s)\n`
      );
      this.broadcastFn?.(fresh.active, fresh.greetings);
    } catch (err) {
      process.stderr.write(`[Suggestions] Generation failed: ${err}\n`);
    } finally {
      this.generating = false;
    }
  }
}

let instance: SuggestionsService | null = null;

export function getSuggestionsService(): SuggestionsService {
  if (!instance) instance = new SuggestionsService();
  return instance;
}

/**
 * @internal — Test-only helper to reset the in-memory cache between test cases.
 * Without this, the module-level cache leaks state across tests.
 */
export function _resetCacheForTesting(): void {
  cachedStore = null;
  persistInFlight = false;
  persistDirty = false;
}
