/**
 * SuggestionsService
 *
 * Maintains a persistent stack of up to 4 AI-generated project improvement
 * suggestions in ~/.mia/suggestions.json. Also generates a batch of 5 greeting
 * messages that cycle on the mobile home screen.
 *
 * Suggestions are generated by a lightweight utility dispatch (same pattern
 * as MemoryExtractor) and are specific to the user's projects based on context
 * gathered from memory facts, git state, and conversation history.
 *
 * Lifecycle:
 *   - On peer connect: maybeGenerate() fills the stack if stale (with cooldown)
 *   - On dismiss / complete: item is archived, no immediate regen
 *   - Periodic: setInterval in daemon/index.ts calls maybeGenerate() every 4h
 */

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join } from 'path';
import { homedir } from 'os';

export interface Suggestion {
  id: string;
  name: string;
  description: string;
  createdAt: number;
}

interface SuggestionsStore {
  active: Suggestion[];
  /** Permanently dismissed — never suggested again */
  dismissed: Suggestion[];
  /** Completed (started) — never suggested again */
  completed: Suggestion[];
  lastGeneratedAt: number;
  /** AI-generated greeting messages that cycle on the mobile home screen */
  greetings: string[];
}

const STORE_PATH = join(homedir(), '.mia', 'suggestions.json');
const MAX_ACTIVE = 4;
/** Regenerate if the stack hasn't been refreshed in 4 hours */
const REGEN_INTERVAL_MS = 4 * 60 * 60 * 1000;
/** Minimum gap between generations to avoid waste (30 minutes) */
const MIN_REGEN_COOLDOWN_MS = 30 * 60 * 1000;
/** Maximum dismissed/completed history entries to include in the prompt */
const MAX_HISTORY_IN_PROMPT = 30;
/** Number of greeting messages to generate per batch */
const GREETINGS_COUNT = 5;

function makeId(): string {
  const ts = String(Date.now()).padStart(15, '0');
  const rand = Math.random().toString(36).substring(2, 8);
  return `sug_${ts}_${rand}`;
}

function loadStore(): SuggestionsStore {
  if (!existsSync(STORE_PATH)) {
    return { active: [], dismissed: [], completed: [], lastGeneratedAt: 0, greetings: [] };
  }
  try {
    const raw = JSON.parse(readFileSync(STORE_PATH, 'utf-8')) as SuggestionsStore;
    // Backfill greetings field for stores created before this feature
    if (!raw.greetings) raw.greetings = [];
    return raw;
  } catch {
    return { active: [], dismissed: [], completed: [], lastGeneratedAt: 0, greetings: [] };
  }
}

function saveStore(store: SuggestionsStore): void {
  try {
    writeFileSync(STORE_PATH, JSON.stringify(store, null, 2), 'utf-8');
  } catch (err) {
    process.stderr.write(`[Suggestions] Save failed: ${err}\n`);
  }
}

type UtilityDispatch = (prompt: string) => Promise<string>;
type BroadcastFn = (suggestions: Suggestion[], greetings: string[]) => void;

export class SuggestionsService {
  private utilityDispatch: UtilityDispatch | null = null;
  private broadcastFn: BroadcastFn | null = null;
  private generating = false;
  private workingDirectory = '';

  setUtilityDispatch(fn: UtilityDispatch): void {
    this.utilityDispatch = fn;
  }

  setBroadcast(fn: BroadcastFn): void {
    this.broadcastFn = fn;
  }

  setWorkingDirectory(dir: string): void {
    this.workingDirectory = dir;
  }

  /** True when an AI generation is currently in flight. */
  isGenerating(): boolean {
    return this.generating;
  }

  /** Return the current active suggestion stack (read-only). */
  getActive(): Suggestion[] {
    return loadStore().active;
  }

  /** Return the current greeting messages batch (read-only). */
  getGreetings(): string[] {
    return loadStore().greetings;
  }

  /**
   * Move a suggestion to the dismissed list.
   * Returns the updated active list. Regeneration happens on the periodic
   * 4-hour interval or next peer connect — not on every dismiss/complete.
   */
  dismiss(id: string): Suggestion[] {
    const store = loadStore();
    const idx = store.active.findIndex(s => s.id === id);
    if (idx !== -1) {
      const [removed] = store.active.splice(idx, 1);
      store.dismissed.push({ ...removed, createdAt: Date.now() });
      saveStore(store);
    }
    return store.active;
  }

  /**
   * Move a suggestion to the completed list.
   * Returns the updated active list. Regeneration happens on the periodic
   * 4-hour interval or next peer connect — not on every dismiss/complete.
   */
  complete(id: string): Suggestion[] {
    const store = loadStore();
    const idx = store.active.findIndex(s => s.id === id);
    if (idx !== -1) {
      const [removed] = store.active.splice(idx, 1);
      store.completed.push({ ...removed, createdAt: Date.now() });
      saveStore(store);
    }
    return store.active;
  }

  /** True if regeneration is needed and enough time has passed since the last generation. */
  isStale(): boolean {
    const store = loadStore();
    const elapsed = Date.now() - store.lastGeneratedAt;
    // Never regenerate within the cooldown window
    if (elapsed < MIN_REGEN_COOLDOWN_MS) return false;
    // Regenerate if underfull, greetings missing, or the refresh interval has expired
    return store.active.length < MAX_ACTIVE || store.greetings.length === 0 || elapsed > REGEN_INTERVAL_MS;
  }

  /**
   * Generate new suggestions only if the stack is stale or underfull.
   * Safe to call frequently — skips immediately if nothing to do.
   */
  async maybeGenerate(): Promise<void> {
    if (!this.isStale()) return;
    await this.generate();
  }

  /**
   * Call the AI to generate new suggestions + a batch of greeting messages
   * in a single prompt. Broadcasts to all connected mobile peers when done.
   */
  async generate(): Promise<void> {
    if (this.generating || !this.utilityDispatch) return;

    const store = loadStore();
    const needed = MAX_ACTIVE - store.active.length;
    if (needed <= 0 && store.greetings.length > 0) return;

    this.generating = true;
    try {
      const dismissedNames = store.dismissed
        .slice(-MAX_HISTORY_IN_PROMPT)
        .map(s => `"${s.name}"`)
        .join(', ');
      const completedNames = store.completed
        .slice(-MAX_HISTORY_IN_PROMPT)
        .map(s => `"${s.name}"`)
        .join(', ');

      const neededSuggestions = Math.max(needed, 0);

      const prompt = `You are an AI assistant for a software developer. Generate two things in a single JSON response.

Working directory: ${this.workingDirectory || 'unknown'}

1. SUGGESTIONS: Generate exactly ${neededSuggestions > 0 ? neededSuggestions : 'no new'} distinct, concrete improvement task suggestion${neededSuggestions !== 1 ? 's' : ''} for the developer's current projects.
   - Each must be immediately actionable (not vague)
   - Focus on: code quality, test coverage, refactoring, documentation, performance, security, dependency hygiene, or tooling
   - Make it specific to what you know about the projects — avoid generic advice
   - Keep names short and imperative (5–8 words max)
   - Keep descriptions concise (1–2 sentences maximum)
   ${dismissedNames ? `\n   Do NOT suggest anything similar to these dismissed: ${dismissedNames}` : ''}
   ${completedNames ? `\n   Do NOT suggest anything similar to these completed: ${completedNames}` : ''}

2. GREETINGS: Generate exactly ${GREETINGS_COUNT} short, varied greeting messages for the home screen.
   - Warm, witty, and developer-flavoured
   - Each under 8 words
   - Vary the tone: one motivational, one curious, one playful, one focused, one understated
   - Do NOT use "Hello" or "Hi" — be more creative

Respond with ONLY a valid JSON object — no markdown fences, no explanation:
{
  "suggestions": [
    { "name": "Short imperative phrase", "description": "One or two sentences." }
  ],
  "greetings": [
    "What are we shipping today?",
    "Ready to break something good?",
    "Let's make the code better.",
    "Something needs fixing. Let's find it.",
    "Code, coffee, repeat."
  ]
}`;

      const result = await this.utilityDispatch(prompt);

      // Strip any markdown fences the model might have added
      const cleaned = result.replace(/```[a-z]*\n?/gi, '').trim();
      const jsonMatch = cleaned.match(/\{[\s\S]*\}/);
      if (!jsonMatch) {
        process.stderr.write(`[Suggestions] No JSON object found in generation result\n`);
        return;
      }

      const parsed = JSON.parse(jsonMatch[0]) as {
        suggestions?: Array<{ name?: string; description?: string }>;
        greetings?: unknown[];
      };

      // Process suggestions
      const newSuggestions: Suggestion[] = (parsed.suggestions ?? [])
        .filter(s => s.name && s.description && typeof s.name === 'string')
        .slice(0, neededSuggestions)
        .map(s => ({
          id: makeId(),
          name: (s.name as string).trim().slice(0, 80),
          description: (s.description as string).trim().slice(0, 300),
          createdAt: Date.now(),
        }));

      // Process greetings
      const newGreetings: string[] = (parsed.greetings ?? [])
        .filter((g): g is string => typeof g === 'string' && g.trim().length > 0)
        .slice(0, GREETINGS_COUNT)
        .map(g => g.trim().slice(0, 60));

      // Reload to avoid clobbering concurrent writes
      const fresh = loadStore();
      if (newSuggestions.length > 0) {
        fresh.active.push(...newSuggestions);
      }
      if (newGreetings.length > 0) {
        fresh.greetings = newGreetings;
      }
      fresh.lastGeneratedAt = Date.now();
      saveStore(fresh);

      process.stderr.write(
        `[Suggestions] Generated ${newSuggestions.length} suggestion(s) and ${newGreetings.length} greeting(s)\n`
      );
      this.broadcastFn?.(fresh.active, fresh.greetings);
    } catch (err) {
      process.stderr.write(`[Suggestions] Generation failed: ${err}\n`);
    } finally {
      this.generating = false;
    }
  }
}

let instance: SuggestionsService | null = null;

export function getSuggestionsService(): SuggestionsService {
  if (!instance) instance = new SuggestionsService();
  return instance;
}
